# Project
version=11.0.0
group=com.grim3212.assorted.core
# Mod Options
mod_id=assortedcore
mod_name=Assorted Core
mod_description=Provides a bunch of new ores that the other Assorted Mods are able to use.
# The mods included in this one.
bundled_mods=machines,ores
# Publishing
# Where a release gets uploaded. Leave an id blank to skip that site.
modrinth_id=Kqp5OpJt
curseforge_id=426885
# The CurseForge project's name from its URL.
curseforge_slug=assorted-core
